ocp-console-notification:
  ## The name of the ConsoleNotification resource in the cluster
  name: "banner-env"

  ## The background color that should be used for the banner
  backgroundColor: teal
  ## The color of the text that will appear in the banner
  color: "#90EE90"
  ## The location of the banner. Options: BannerTop, BannerBottom, BannerTopBottom
  location: BannerTop
  ## The text that should be displayed in the banner. This value is required for the banner to be created
  text: "Dry run for Sterling"